version: "3.9"

services:
  app:
    build:
      context: .
      target: runner         
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    command: npm run start

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  seed:
    build:
      context: .
      target: seed           
    command: npm run seed
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/rentkar
    restart: "no"